export interface Empresa {
  empresa_id: number;
  nombre: string;
  habilitado: number;
  created_at?: number;
  updated_at?: number;
}

export interface Persona {
  apellido_materno: string;
  apellido_paterno: string;
  cargo?: string;
  cargos_id?: number;
  cargos?: any;
  centro_costo_encargado?: number;
  centro_costo_id?: number;
  ci_extension?: string;
  ci_origen?: string;
  ci?: string;
  ciudad: string;
  codigo: number;
  correo?: string;
  created_at?: number;
  division_id?: number;
  empresa_id?: number;
  empresa: Empresa;
  fecha_nacimiento?: string;
  foto?: string;
  habilitado: number;
  nombre_completo: string;
  nombre?: string;
  persona_id: number;
  telefono?: string;
  ubicacion?: string;
  unidad_negocio_id: number;
  unidad_organizativa_id?: number;
  updated_at?: number;
  user: any;
}

export interface Rol {
  rol_id: number;
  aplicacion_id: number;
  nombre: string;
  habilitado: number;
  created_at?: number;
  updated_at?: number;
  aplicacion: Aplicacion;
  modulos: Modulo[];
  users: any[];
}

export interface User {
  id: number;
  created_at: number;
  email: string;
  habilitado: number;
  name: string;
  persona_id: number;
  updated_at: number;
  persona: Persona;
  roles: Rol[];
}

export interface Operacion {
  operacion_id: number;
  nombre: string;
  created_at?: number;
  updated_at?: number;
}

export interface Bitacora {
  bitacora_id: number;
  codigo_app: string;
  fecha: Date;
  nombre_completo: string;
  operacion: string;
  tabla_identificador: number;
  tabla: string;
}

export interface Aplicacion {
  aplicacion_id: number;
  area?: string;
  base_datos?: string;
  codigo_nombre: string;
  codigo: string;
  created_at?: number;
  descripcion: string;
  habilitado: number;
  icono: string;
  ip_servidor?: string;
  modulos: Modulo[];
  nombre: string;
  roles: Rol[];
  titulo: string;
  updated_at?: number;
  url: string;
  version: string;
}

export interface Modulo {
  aplicacion_id: number;
  aplicacion_nombre: string;
  aplicacion: Aplicacion;
  check: boolean;
  created_at?: number;
  habilitado: number;
  icono: string;
  menu: number;
  modulo_id: number;
  modulo_padre?: number | null;
  nombre: string;
  SubModulos: Modulo[];
  titulo: string;
  updated_at?: number;
  url: string;
}

export interface RolAcceso {
  acceso_id: number;
  rol_id: number;
  modulo_id: number;
  nombre: string;
  titulo: string;
  url: string;
}

export interface Componente {
  componente_id: number;
  habilitado: number;
  nombre: string;
}

export interface RolAsignacion {
  aplicacion_id: number;
  codigo_app: string;
  componente_id: number;
  editable: number;
  habilitado: number;
  nombre: string;
  rol_asignacion_id: number;
  rol_id: number;
  rol: string;
  visible: number;
}

export interface AuhtUser {
  persona: Persona;
  aplicacion: Aplicacion;
}

export interface MenuItem {
  IdRol: number;
  NombreRol: string;
  IdModulo: number;
  IdModuloPadre?: number;
  TituloModulo: string;
  NombreModulo: string;
  RutaModulo: string;
  Menu: number;
}

export interface BackendResponse {
  success: boolean;
  message: string;
  data: any;
}

export interface UsuarioRol {
  usuario_rol_id: number;
  user_id: number;
  rol_id: number;
  usuario?: any;
  rol?: any;
}

export interface Producto {
  id: number;
  name: string;
  price: number;
  stock: number;
  created_at: Date;
  updated_at: Date;
  habilitado: number;
}

export interface ItemProducto {
  id: number;
  name: string;
  price: string;
  quantity: number;
}

export interface Venta {
  id: number;
  cliente_id: number;
  total: string;
  created_at: Date;
  updated_at: Date;
  cliente_name: string;
  detalle: DetalleVenta[];
}

export interface Cliente {
  id: number;
  name: string;
  email: string;
  phone: string;
  created_at: Date;
  updated_at: Date;
}

// Generated by https://quicktype.io

export interface DetalleVenta {
  created_at: Date;
  id: number;
  price: string;
  product_name: string;
  producto_id: number;
  quantity: number;
  total: string;
  updated_at: Date;
  venta_id: number;
}
