export enum StorageKeys {
  ACCESOS = "_accesos",
  APLICACION = "_aplicacion",
  MODULOS = "_modulos",
  PERSONA = "_persona",
  ROL = "_rol",
  USER = "_user",
  USER_TOKEN = "_token",
  LOGGED = "_logged",
  CARGO = "_cargo",
}

// Los nombres de los modulos deben ir en plural
export enum ModulosSistema {
  ACCESOS = "accesos",
  APLICACIONES = "aplicaciones",
  ASIGNAR_CARGOS = "asignar_cargos",
  BITACORA = "bitacora",
  CARGOS = "cargos",
  CENTROS_COSTO = "centros_costo",
  COMPONENTES = "componentes",
  DIVISIONES = "divisiones",
  EMPRESA = "empresas",
  MODULOS = "modulos",
  PERSONAS = "personas",
  PERSONAS_CENTROS_COSTO = "personascc",
  ROL_ASIGNACION = "rol_asignacion",
  ROLES = "roles",
  UNIDADES_NEGOCIO = "unidades_negocio",
  UNIDADES_ORGANIZATIVAS = "unidades-organizativas",
  USUARIOS = "users",
  PRODUCTOS = "productos",
  VENTAS = "ventas",
}

export enum TipoAcceso {
  INDEX = "_index",
  INSERT = "_insert",
  UPDATE = "_update",
  DELETE = "_delete",
}

export enum ApiEndpoints {
  ACCESOS = "accesos",
  ACTUALIZAR_CARGOS = "personas/update-cargo",
  ACTUALIZAR_ENCARGADO_PCC = "personascc/update-encargado",
  APLICACIONES = "aplicaciones",
  APLICACIONES_CON_ROLES = "aplicaciones?habilitado=1&roles=1",
  BITACORA = "bitacoras",
  CARGOS = "cargos",
  CENTROS_COSTO = "centros-costo",
  COMPONENTES = "componentes",
  DIVISIONES = "divisiones",
  ELIMINAR_ASIGNACION_PCC = "personas-centro-costos/eliminar-asignacion",
  ELIMINAR_USUARIO_ROL = "eliminar-usuario-rol",
  EMPRESAS = "empresas",
  FILTRAR_PERSONAS = "personas/filtrar",
  HABILITAR_COMPONENTES = "componentes/habilitar",
  HABILITAR_EMPRESAS = "empresas/habilitar",
  HABILITAR_MODULOS = "modulos/habilitar",
  HABILITAR_PERSONAS = "personas/habilitar",
  HABILITAR_ROL_ASIGNACION = "rol-asignaciones/habilitar",
  HABILITAR_ROLES = "roles/habilitar",
  HABILITAR_USERS = "users/habilitar",
  IMPORTAR_PERSONAS = "personas-upload",
  LOGIN = "aut/login",
  MODULOS = "modulos",
  MODULOS_BY_APP = "modulos/app",
  PERSONAS = "personas",
  PERSONAS_CENTROS_COSTO = "personascc",
  ROL_ASIGNACION = "rol-asignaciones",
  ROLES = "roles",
  ROLES_ACCESOS = "roles/accesos",
  UNIDAD_NEGOCIO = "unidades-negocio",
  UNIDADES_ORGANIZATIVAS = "unidades-organizativas",
  USERS = "users",
  USUARIO_ROL = "usuario-rol",
  USUARIO_ROL_BASE = "usuario-rol/set-rol-base",
  ASIGNAR_CARGOS = "asignar-cargos",

  //-------
  PRODUCTOS = "productos",
  VENTAS = "ventas",
  CLIENTES = "clientes",
}

export enum Messages {
  NO_SE_PUDO_COMPLETAR = "No se pudo completar la operación",
  OPERACION_CORRECTA = "Operación correcta",
}

// export enum IconNames {
//   Add = 'Add',
//   AddCircle = 'AddCircle',
//   AddPhoto = 'AddPhotoAlternateIcon',
//   Android = 'Android',
//   Apple = 'Apple',
//   Apps = 'Apps',
//   Archive = 'Archive',
//   AttachFile = 'AttachFile',
//   Backup = 'Backup',
//   Block = 'Block',
//   Bolt = 'Bolt',
//   Bookmark = 'Bookmark',
//   Build = 'Build',
//   Business = 'Business',
//   CalendarMonthIcon = 'CalendarMonthIcon',
//   Call = 'Call',
//   CameraAlt = 'CameraAlt',
//   Check = 'Check',
//   CLOCK = 'AccessTime',
//   Close = 'Close',
//   Coffee = 'Coffee',
//   Computer = 'Computer',
//   ContentCopy = 'ContentCopy',
//   ContentCut = 'ContentCut',
//   ContentPaste = 'ContentPaste',
//   Home = 'Home',
//   Man = 'Accessibility',
//   PeopleAlt = 'PeopleAlt',
//   Extension = 'Extension',
//   Wallet = 'AccountBalanceWalletIcon',
// }
